site_name: dynamiqs
site_url: "https://www.dynamiqs.org"
use_directory_urls: false
repo_url: https://github.com/dynamiqs/dynamiqs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.path
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  logo: media/logo.png
  favicon: media/favicon.ico
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      custom_templates: docs/templates
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            heading_level: 2
            members_order: source
            docstring_section_style: list
            show_signature_annotations: true
            separate_signature: true
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
watch:
  - dynamiqs
nav:
  - Home: index.md
  - Getting started:
      - getting_started/index.md
      - Installation: getting_started/installation.md
      - First steps: getting_started/first_steps.md
  - Tutorials:
      - tutorials/index.md
      - Optimal control: tutorials/optimal_control.md
      - SNAP: tutorials/snap.md
      - ECD: tutorials/ecd.md
  - Reference:
      - reference/index.md
      - dynamiqs.utils:
          - utils: reference/utils/utils.md
