site_name: dynamiqs
site_url: "https://www.dynamiqs.org"
use_directory_urls: false
repo_url: https://github.com/dynamiqs/dynamiqs
repo_name: dynamiqs
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
    admonition:
      example: material/human-male-board
  logo: media/logo.png
  favicon: media/favicon.svg
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
copyright: "&copy Copyright 2023, dynamiqs developers."
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dynamiqs/dynamiqs
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/dynamiqs-org/shared_invite/zt-1z4mw08mo-qDLoNx19JBRtKzXlmlFYLA
extra_css:
  - stylesheets/extra.css
  - stylesheets/theme.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
plugins:
  - search
  - glightbox:
      effect: fade
      slide_effect: slide
      width: 70%
      zoomable: false
      draggable: false
  - mkdocs-simple-hooks:
      hooks:
        on_env: "docs.hooks:on_env"
  - gen-files:
      scripts:
        - docs/generate_python_api.py
  - mkdocstrings:
      default_handler: python
      custom_templates: docs/templates
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            heading_level: 1
            members_order: source
            docstring_section_style: list
            show_signature_annotations: true
            separate_signature: true
            line_length: 88
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - attr_list
  - footnotes
  - md_in_html
extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
watch:
  - dynamiqs
validation:
  nav:
    omitted_files: warn
    not_found: warn
    absolute_links: warn
  links:
    not_found: warn
    absolute_links: ignore
    unrecognized_links: warn
nav:
  - Home: index.md
  - Getting started:
      - getting_started/index.md
      - What is dynamiqs?: getting_started/whatis.md
      - Installation: getting_started/installation.md
      - Basic examples: getting_started/examples.md
      - Contributing: getting_started/contributing.md
      - Let's talk!: getting_started/talk.md
  - Tutorials:
      - tutorials/index.md
      - Basics:
          - Workflow in dynamiqs: tutorials/workflow.md
          - tutorials/defining-hamiltonians.md
          - tutorials/closed-system.md
          - tutorials/open-system.md
          - tutorials/batching.md
          - tutorials/gpu.md
  - Python API:
      - python_api/index.md
      - Solvers:
          - sesolve: python_api/solvers/sesolve.md
          - mesolve: python_api/solvers/mesolve.md
          - smesolve: python_api/solvers/smesolve.md
      - Utilities:
          - Operators:
              - eye: python_api/utils/operators/eye.md
              - zero: python_api/utils/operators/zero.md
              - destroy: python_api/utils/operators/destroy.md
              - create: python_api/utils/operators/create.md
              - number: python_api/utils/operators/number.md
              - parity: python_api/utils/operators/parity.md
              - displace: python_api/utils/operators/displace.md
              - squeeze: python_api/utils/operators/squeeze.md
              - quadrature: python_api/utils/operators/quadrature.md
              - position: python_api/utils/operators/position.md
              - momentum: python_api/utils/operators/momentum.md
              - sigmax: python_api/utils/operators/sigmax.md
              - sigmay: python_api/utils/operators/sigmay.md
              - sigmaz: python_api/utils/operators/sigmaz.md
              - sigmap: python_api/utils/operators/sigmap.md
              - sigmam: python_api/utils/operators/sigmam.md
          - States:
              - fock: python_api/utils/states/fock.md
              - fock_dm: python_api/utils/states/fock_dm.md
              - coherent: python_api/utils/states/coherent.md
              - coherent_dm: python_api/utils/states/coherent_dm.md
          - Quantum utilities:
              - dag: python_api/utils/utils/dag.md
              - trace: python_api/utils/utils/trace.md
              - ptrace: python_api/utils/utils/ptrace.md
              - tensprod: python_api/utils/utils/tensprod.md
              - expect: python_api/utils/utils/expect.md
              - norm: python_api/utils/utils/norm.md
              - unit: python_api/utils/utils/unit.md
              - dissipator: python_api/utils/utils/dissipator.md
              - lindbladian: python_api/utils/utils/lindbladian.md
              - isket: python_api/utils/utils/isket.md
              - isbra: python_api/utils/utils/isbra.md
              - isdm: python_api/utils/utils/isdm.md
              - isop: python_api/utils/utils/isop.md
              - toket: python_api/utils/utils/toket.md
              - tobra: python_api/utils/utils/tobra.md
              - todm: python_api/utils/utils/todm.md
              - braket: python_api/utils/utils/braket.md
              - overlap: python_api/utils/utils/overlap.md
              - fidelity: python_api/utils/utils/fidelity.md
          - Tensor conversion:
              - to_tensor: python_api/utils/tensor_types/to_tensor.md
              - to_qutip: python_api/utils/tensor_types/to_qutip.md
              - to_numpy: python_api/utils/tensor_types/to_numpy.md
              - from_qutip: python_api/utils/tensor_types/from_qutip.md
          - Wigner distribution:
              - wigner: python_api/utils/wigners/wigner.md
          - Vectorization:
              - operator_to_vector: python_api/utils/vectorization/operator_to_vector.md
              - vector_to_operator: python_api/utils/vectorization/vector_to_operator.md
              - spre: python_api/utils/vectorization/spre.md
              - spost: python_api/utils/vectorization/spost.md
              - sprepost: python_api/utils/vectorization/sprepost.md
              - sdissipator: python_api/utils/vectorization/sdissipator.md
              - slindbladian: python_api/utils/vectorization/slindbladian.md
          - Quantum optimal control:
              - rand_complex: python_api/utils/optimal_control/rand_complex.md
              - pwc_pulse: python_api/utils/optimal_control/pwc_pulse.md
              - snap_gate: python_api/utils/optimal_control/snap_gate.md
              - cd_gate: python_api/utils/optimal_control/cd_gate.md
          - Plotting:
              - plot_wigner: python_api/plots/misc/plot_wigner.md
              - plot_pwc_pulse: python_api/plots/misc/plot_pwc_pulse.md
              - plot_fock: python_api/plots/misc/plot_fock.md
              - plot_fock_evolution: python_api/plots/misc/plot_fock_evolution.md
