site_name: dynamiqs
site_url: "https://www.dynamiqs.org"
use_directory_urls: false
repo_url: https://github.com/dynamiqs/dynamiqs
repo_name: dynamiqs
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  logo: media/logo.png
  favicon: media/favicon.svg
  palette:
    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
copyright: "&copy Copyright 2023, dynamiqs developers."
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dynamiqs/dynamiqs
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/t/dynamiqs-org/shared_invite/zt-1z4mw08mo-qDLoNx19JBRtKzXlmlFYLA
extra_css:
  - stylesheets/extra.css
  - stylesheets/jupyter.css
plugins:
  - search
  - gen-files:
      scripts:
        - docs/generate_python_api.py
  - literate-nav:
      nav_file: navigation.md
  - section-index
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      custom_templates: docs/templates
      handlers:
        python:
          options:
            show_source: false
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            heading_level: 1
            members_order: source
            docstring_section_style: list
            show_signature_annotations: true
            separate_signature: true
            line_length: 88
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
watch:
  - dynamiqs
nav:
  - Home: index.md
  - Getting started:
      - getting_started/index.md
      - What is dynamiqs?: getting_started/whatis.md
      - Installation: getting_started/installation.md
      - First examples: getting_started/examples.md
      - Contributing: getting_started/contributing.md
      - Let's dicuss: getting_started/discussion.md
  - Tutorials:
      - tutorials/index.md
      - Simulating quantum dynamics: tutorials/simulatingdynamics.ipynb
  - Python API: python_api/
