[project]
name = "torchqdynamics"
version = "0.1.0"
description = "Quantum systems simulation with PyTorch."
dependencies = [
    "qutip",
    "numpy",
    "matplotlib",
    "tqdm",
    "torch",
    "torchdiffeq",
]

[project.optional-dependencies]
dev = [
    "taskipy",
    "isort",
    "black[jupyter]",
    "codespell",
    "flake8",
    "pytest",
    "pytest-sugar",
    "mkdocs-material",
]

[tool.setuptools]
packages = ["torchqdynamics"]

[tool.isort]
profile = "black"
skip = ["__init__.py"]
skip_gitignore = true

[tool.black]
preview = true
target-version = ["py38"]
skip-string-normalization = true
jupyter = true

[tool.codespell]
skip = ".git,*.ipynb"
ignore-words-list = "ket, braket"

[tool.taskipy.tasks]
isort = { cmd = "echo '\n>>> isort' && isort .", help = "sort the imports (isort)" }
black = { cmd = "echo '\n>>> black' && black .", help = "auto-format the code (black)" }
codespell = { cmd = "echo '\n>>> codespell' && codespell tests torchqdynamics", help = "check for misspellings (codespell)" }
flake8 = { cmd = "echo '\n>>> flake8' && flake8 tests torchqdynamics", help = "check code style (flake8)" }
lint = { cmd = "task isort && task black && task codespell && task flake8", help = "lint the code and check style (isort + black + codespell + flake8)" }
test = { cmd = "echo '\n>>> pytest -v -m \"not long\"' && pytest -v -m \"not long\"", help = "run the unit tests suite excluding long tests (pytest)" }
test-long = { cmd = "echo '\n>>> pytest -v -m \"long\"' && pytest -v -m \"long\"", help = "run the unit tests suite including only long tests (pytest)" }
test-all = { cmd = "echo '\n>>> pytest' && pytest", help = "run the complete unit tests suite (pytest)" }
docbuild = {cmd = "mkdocs build", help = "build the documentation website"}
docserve = {cmd = "mkdocs serve", help = "preview documentation website with hot-reloading"}
all = { cmd = "task lint && task test", help = "run all tasks before a commit (isort + black + codespell + flake8 + pytest)" }
ci = { cmd = """echo '\n>>> isort' && isort --check . &&
                echo '\n>>> black' && black --check . &&
                task codespell &&
                task flake8 &&
                task test &&
                task docbuild""", help = "run all the CI checks" }
