[project]
name = "torchqdynamics"
version = "0.1.0"
description = "Quantum systems simulation with PyTorch."
dependencies = [
    "qutip",
    "numpy",
    "matplotlib",
    "tqdm",
    "torch",
    "torchdiffeq",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["torchqdynamics"]

[tool.yapf]
based_on_style = "facebook"
column_limit = 88
split_before_named_assigns = false

[tool.isort]
profile = "black"
line_length = 88  # to be consistent with yapf
skip = ["__init__.py"]
src_paths = ["torchqdynamics", "tests"]
