[project]
name = "dynamiqs"
version = "0.1.0"
description = "Quantum systems simulation with PyTorch."
dependencies = [
    "qutip",
    "numpy",
    "matplotlib",
    "tqdm",
    "torch",
    "methodtools",
]

[project.optional-dependencies]
dev = [
    "taskipy",
    "isort",
    "black[jupyter]",
    "codespell",
    "flake8",
    "pytest",
    "pytest-sugar",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-gen-files",
    "mkdocs-literate-nav",
    "mkdocs-section-index",
]

[tool.setuptools]
packages = ["dynamiqs"]

[tool.isort]
profile = "black"
skip = ["__init__.py"]
skip_gitignore = true

[tool.black]
preview = true
target-version = ["py38"]
skip-string-normalization = true
jupyter = true

[tool.codespell]
skip = ".git,*.ipynb"
ignore-words-list = "ket, braket"

[tool.taskipy.tasks]
isort = { cmd = "echo '\n>>> isort' && isort .", help = "sort the imports (isort)" }
black = { cmd = "echo '\n>>> black' && black .", help = "auto-format the code (black)" }
codespell = { cmd = "echo '\n>>> codespell' && codespell tests dynamiqs", help = "check for misspellings (codespell)" }
flake8 = { cmd = "echo '\n>>> flake8' && flake8 tests dynamiqs", help = "check code style (flake8)" }
lint = { cmd = "task isort && task black && task codespell && task flake8", help = "lint the code and check style (isort + black + codespell + flake8)" }
test = { cmd = "echo '\n>>> pytest -v -m \"not long\"' && pytest -v -m \"not long\"", help = "run the unit tests suite excluding long tests (pytest)" }
test-long = { cmd = "echo '\n>>> pytest -v -m \"long\"' && pytest -v -m \"long\"", help = "run the unit tests suite including only long tests (pytest)" }
test-all = { cmd = "echo '\n>>> pytest' && pytest", help = "run the complete unit tests suite (pytest)" }
doctest-code = { cmd = "echo '\n>>> doctest dynamiqs/' && pytest --doctest-modules dynamiqs", help = "check code docstrings examples (doctest)" }
doctest-docs = { cmd = "echo '\n>>> doctest docs/' && pytest --doctest-modules docs --doctest-glob '*.md' --ignore-glob 'python_api'", help = "check documentation examples (doctest)" }
doctest = { cmd = "task doctest-code && task doctest-docs", help = "check all examples (doctest)" }
docbuild = { cmd = "mkdocs build", help = "build the documentation website" }
docserve = { cmd = "mkdocs serve", help = "preview documentation website with hot-reloading" }
all = { cmd = "task lint && task test && task doctest", help = "run all tasks before a commit (isort + black + codespell + flake8 + pytest + doctest)" }
ci = { cmd = """echo '\n>>> isort' && isort --check . &&
                echo '\n>>> black' && black --check . &&
                task codespell &&
                task flake8 &&
                task test &&
                task doctest &&
                task docbuild""", help = "run all the CI checks" }
