[project]
name = "torchqdynamics"
version = "0.1.0"
description = "Quantum systems simulation with PyTorch."
dependencies = [
    "qutip",
    "numpy",
    "matplotlib",
    "tqdm",
    "torch",
    "torchdiffeq",
]

[project.optional-dependencies]
dev = [
    "isort",
    "black[jupyter]",
    "pytest",
    "pytest-sugar",
]

[tool.setuptools]
packages = ["torchqdynamics"]

[tool.black]
preview = true
target-version = ["py38"]
skip-string-normalization = true
jupyter = true

[tool.isort]
profile = "black"
skip = ["__init__.py"]
